# A sample of how to config your things!
# I have a outsourced .env secrets to a second file for better secret 
# management

ENVIRONMENT_CONFIG="/home/mattw/DfHaste/src/environment.toml"
FILE_CACHE="../cached_data/"
SQL_LIBRARY="../sql_library/"
