# Welcome to the world of cofiguration.
# Configure db connections to begin the haste!

# These are samples! :)
[[database]]
name="db_1_dev"
driver="cx_oracle"
hostname="server1"
port=1521
[database.auth]
type="basic"
username="me"
password="***"

[[database]]
name="db_1_prod"
driver="pyodbc"
hostname="server2"
port=1521
[database.auth]
type="trusted_connection"

[[database]]
name="db_2_prod"
driver="sqlite3"
path="C:/my_sqlite.db"
